### ISSUE TITLE
How to import CSS from modules in Meteor 1.3.x

### ISSUE THREAD

**Issue by hexsprite** [juliancwirko/meteor-s-grid#7]
Hi, trying to override some CSS from a npm package and would like to continue to use our stylus setup.

Is this package still supported for 1.3.X or should we be using something else?

Have tried all the variations of importing from another package on this thread but no luck with this package....

https://github.com/meteor/meteor/issues/6037#issuecomment-211601919

**Comment by juliancwirko** [comment]
Hi, this is integrated with Meteor as a Meteor package. It should work with 1.3.x For example [simplechat.support](https://github.com/juliancwirko/s-chat-app/blob/master/client/main.styl) app uses it. 

It works but it's a little bit outdated. 

There is also standalone Npm package: https://www.npmjs.com/package/s-grid You need to decide which one you want to use. In Meteor 1.3 you can use Npm modules so maybe it will be better to use it from Npm. But then you need to provide autoprefixer and Stylus too. Also imports are different. As you can see in the simplechat.support app I import it like:

```
@import 's-grid-settings'
@import 's-grid-functions'
```

Just because I use this Meteor package instead the one from Npm. 
Your link describes ways to import files from Npm packages.

**Comment by hexsprite** [comment]
@juliancwirko thanks for the reply.

So are you saying that I might be better off using the `stylus` package that ships with Meteor 1.3.4.1 instead of `meteor-s-grid` and installing `s-grid` and other required dependencies from npm?

**Comment by juliancwirko** [comment]
yeah, I think you could try, this is the way for new Meteor not just in the case of this package, but all packages which doesn't need Meteor internals, just remember that s-grid from Npm needs autoprefixer. For this you can use my postcss package or seba:minifiers-autoprefixer
